name: Build with JDK 8 and Generate Coverage Report

on:
  pull_request:
    branches:
      - '**' # Match all target branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Step 4: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # Step 5: Build and run tests with Maven
      - name: Build and test with Maven
        run: mvn clean verify

      # Step 6: Generate Jacoco coverage report
      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

      # Step 7: Install diff-cover
      - name: Install diff-cover
        run: |
          python -m pip install --upgrade pip
          pip install diff-cover

      # Step 8: Generate diff coverage and fail if coverage is below 90%
      - name: Check coverage with diff-cover
        run: |
          git diff origin/main > diff.patch
          diff-cover target/site/jacoco/jacoco.xml --compare-branch=main --fail-under=90 --html-report diff-cover-report.html

      # Step 9: Upload diff coverage report as an artifact
      - name: Upload diff coverage report
        uses: actions/upload-artifact@v3
        with:
          name: diff-cover-report
          path: diff-cover-report.html