name: Show branch name of pull request

on:
  pull_request:
    branches:
      - '**'
  issue_comment:
    types:
      - created

env:
  GH_TOKEN: ${{ github.token }}
jobs:
  test-and-coverage:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    if: >
      github.event.comment.body == '/show' &&  github.event.issue.pull_request != null
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name (Non pull requests)
        if: github.event_name != 'pull_request'
        id: branch-name
        shell: bash
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.BRANCH_NAME }}

      - name: Find branch name using GH CLIs
        id: get_branch
        run: |
          # Get PR number from the event payload
          PR_NUMBER=${{ github.event.issue.number }}
          
          # Fetch PR details using GitHub CLI
          PR_BRANCH=$(gh pr view $PR_NUMBER --json headRefName -q '.headRefName')
          
          # Save the branch name as an output variable
          echo "branch_name=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Display branch name
        run: echo "The branch name is ${{ steps.get_branch.outputs.branch_name }}"

